# Generated by Django 5.1.4 on 2025-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reasoning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('version_tag', models.CharField(max_length=50)),
                ('security_tag', models.CharField(max_length=50)),
            ],
        ),
    ]
