# Generated by Django 5.1.4 on 2025-01-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_text_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoning',
            name='access_tag',
            field=models.CharField(default='all', max_length=20),
        ),
    ]
